### ISSUE TITLE
Allow for silent execution

### ISSUE THREAD

**Issue by JonahMMay** [AsBuiltReport/AsBuiltReport.Veeam.VBR#164]
### Veeam Backup & Replication version

12.1

### Description

I am trying to configure this to run as a periodically scheduled task, however I cannot get the module to skip prompting for information like the Author name, even with the sample config that I generated beforehand.

### Before submitting

- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this change request.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Veeam.VBR/issues) before submitting this change request.

**Comment by rebelinux** [comment]
Hello,

These are the parameters I use to create the scheduling task:

-NoProfile -ExecutionPolicy Bypass -Command "New-AsBuiltReport -Report Veeam.VBR -Target veeam-vbr.pharmax.local -AsBuiltConfigFilePath C:\AsBuiltReport\AsBuiltReport.json -OutputFolderPath C:\AsBuiltReport\ -Username 'domain\User' -Password 'p@ssw0rd' -Format HTML -ReportConfigFilePath C:\AsBuiltReport\AsBuiltReport.Veeam.VBR.json -EnableHealthCheck -Timestamp"

![image](https://github.com/user-attachments/assets/f5b4ae21-35a8-4294-b949-afd6b0bf20f1)

It is required to generate both JSON files so that it can be referenced within the task. 

https://github.com/AsBuiltReport/AsBuiltReport.Core?tab=readme-ov-file#new-asbuiltconfig
-AsBuiltConfigFilePath C:\AsBuiltReport\AsBuiltReport.json

https://github.com/AsBuiltReport/AsBuiltReport.Veeam.VBR?tab=readme-ov-file#pencil2-configuration
-ReportConfigFilePath C:\AsBuiltReport\AsBuiltReport.Veeam.VBR.json

It would be a good idea to create a cmdlet for this purpose but it would be necessary to add it to the AsBuiltReport.Core.
